using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Portal : MonoBehaviour
{
    [SerializeField]
    public string transferMapName; // ì´ë™í•  ë§µ ì´ë¦„

    private Player thePlayer;
    private EnemyManager enemyManager;
    public AudioClip usingportal;
    private AudioSource audioSource;

    void Start()
    {
        audioSource = GetComponent<AudioSource>();
        if (thePlayer == null)
        {
            thePlayer = FindFirstObjectByType<Player>();
        }

        enemyManager = FindFirstObjectByType<EnemyManager>();
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            // ëª¨ë“  ëª¬ìŠ¤í„°ê°€ ì£½ì—ˆëŠ”ì§€ í™•ì¸
            if (enemyManager != null && enemyManager.TotalRemainingEnemies <= 0)
            {
                Debug.Log("ğŸšª Portal Triggered!");
                Debug.Log("ğŸ“¦ transferMapName = [" + transferMapName + "]");

                thePlayer.currentMapName = transferMapName;
                Debug.Log("âœ… currentMapName ì„¤ì • ì™„ë£Œ: " + thePlayer.currentMapName);

                StartCoroutine(LoadNextScene());
            }
            else
            {
                Debug.Log("â— ì•„ì§ ëª¨ë“  ì ì„ ë‹¤ ì£½ì´ì§€ ëª»í–ˆì–´..!");
            }
        }
    }

    private IEnumerator LoadNextScene()
    {
        yield return null; // í•œ í”„ë ˆì„ ëŒ€ê¸°í•´ì„œ currentMapName ì„¤ì •ì´ ë°˜ì˜ë˜ê²Œ í•¨
        audioSource.PlayOneShot(usingportal);
        SceneManager.LoadScene(transferMapName);
    }
}
